services:
  flet-app:
    build:
      context: .
    ports:
      - 7860:8000
    develop:
      watch:
        - path: .
          action: rebuild
    depends_on:
      - db
  db:
    image: mongo
    volumes: 
     - database:/data/db
    ports:
      - 27017:27017
volumes:
  database: